[project]
name = "class-pet"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pynput>=1.8.2",
    "PySide6>=6.8",
    "pyside6-fluent-widgets>=1.11.3",
    "tendo>=0.3.0",
]

[tool.uv]
package = false

[dependency-groups]
dev = [
    "pillow>=12.3.0",
    "pyinstaller>=6.22.3",
    "ruff>=0.16.8",
]
